#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

ROS_MASTER_URI="http://ros:11311"
source /opt/ros/noetic/setup.bash

cd /lunabotics/ros/catkin_ws/src

# Setup webots ros
apt-get update && apt-get install -q -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

git clone https://github.com/cyberbotics/webots_ros.git

cd /lunabotics/ros/catkin_ws

rosdep update
rosdep install --from-paths src --ignore-src --rosdistro noetic


catkin_make
