FROM ros:noetic-ros-core

RUN apt-get update -y

# Standard tools
RUN apt-get install -y clang make gcc g++ inetutils-ping net-tools git tmux

# 2. Install ROS packages from apt.
RUN apt-get install -y \
    ros-noetic-move-base \
    ros-noetic-rviz \
    ros-noetic-rosmon \
    ros-noetic-tf2-tools \
    ros-noetic-robot-state-publisher \
    ros-noetic-joint-state-publisher \
    ros-noetic-realsense2-camera \
    ros-noetic-ompl \
    ros-noetic-grid-map-core \
    ros-noetic-grid-map-ros \
    ros-noetic-eigen-conversions \
    ros-noetic-gazebo-ros

RUN apt-get install -y ros-noetic-robot-pose-ekf

COPY ros/scripts /ros/scripts
COPY ros/catkin_ws/.catkin_workspace /ros/catkin_ws/.catkin_workspace
COPY ros/catkin_ws/src /ros/catkin_ws/src
COPY can /can

RUN cd /ros/catkin_ws && \
    rm -rf /ros/catkin_ws/build /ros/catkin_ws/devel && \
    /ros_entrypoint.sh catkin_make

# Add /catkin_ws to the ROS environment.
COPY ros/ros_entrypoint.sh /ros_entrypoint.sh
