FROM ros:noetic-ros-core

RUN apt-get update -y

RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y libpcl-dev
# Standard tools
RUN apt-get install -y \
    clang \
    make \
    gcc \
    g++ \
    inetutils-ping \
    net-tools \
    git \
    tmux \
    python3-catkin-tools \
    libeigen3-dev

# 2. Install ROS packages from apt.
RUN apt-get install -y \
    ros-noetic-roscpp \
    ros-noetic-eigen-conversions \
    ros-noetic-gazebo-ros \
    ros-noetic-grid-map-core \
    ros-noetic-grid-map-ros \
    ros-noetic-joint-state-publisher \
    ros-noetic-move-base \
    ros-noetic-ompl \
    ros-noetic-realsense2-camera \
    ros-noetic-robot-pose-ekf \
    ros-noetic-robot-state-publisher \
    ros-noetic-rosmon \
    ros-noetic-rviz \
    ros-noetic-tf2-tools \
    ros-noetic-usb-cam \
    ros-noetic-compressed-image-transport \
    ros-noetic-rosmon \
    ros-noetic-pcl-ros \
    ros-noetic-tf-conversions \
    ros-noetic-grid-map-filters \
    ros-noetic-grid-map-rviz-plugin \
    ros-noetic-xacro \
    ros-noetic-teb-local-planner

# Install visual and debugging tools
RUN apt-get install -y \
    ros-noetic-rosbag \
    ros-noetic-plotjuggler \
    ros-noetic-rqt-tf-tree \
    ros-noetic-rqt-plot \
    ros-noetic-rqt-image-view 

RUN apt-get install -y software-properties-common
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE \
    || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
RUN add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u
RUN apt-get update
RUN apt-get install -y \
    ros-noetic-librealsense2 \
RUN apt-cache search realsense

COPY ros/scripts /ros/scripts
COPY ros/catkin_ws/.catkin_workspace /ros/catkin_ws/.catkin_workspace

# Incremental-ish builds to avoid full rebuilds. Keep these in order
# from least to most often changed.
# Uncomment the ones to be compiled
COPY ros/catkin_ws/src/kindr /ros/catkin_ws/src/kindr
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY ros/catkin_ws/src/kindr_ros /ros/catkin_ws/src/kindr_ros
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY ros/catkin_ws/src/message_logger /ros/catkin_ws/src/message_logger
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY ros/catkin_ws/src/realsense-ros /ros/catkin_ws/src/realsense-ros
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY ros/catkin_ws/src/elevation_mapping /ros/catkin_ws/src/elevation_mapping
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY ros/catkin_ws/src/elevation_mapping_demos /ros/catkin_ws/src/elevation_mapping_demos
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY can /can

COPY ros/catkin_ws/src/motor_bridge /ros/catkin_ws/src/motor_bridge
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY ros/catkin_ws/src/pad_send /ros/catkin_ws/src/pad_send
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY ros/catkin_ws/src/david_navigation /ros/catkin_ws/src/david_navigation
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

COPY ros/catkin_ws/src/david_config /ros/catkin_ws/src/david_config
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

# Build any packages not listed above.
RUN rm -rf /ros/catkin_ws/src
COPY ros/catkin_ws/src /ros/catkin_ws/src
RUN cd /ros/catkin_ws && /ros_entrypoint.sh catkin build

# Add /catkin_ws to the ROS environment.
COPY ros/ros_entrypoint.sh /ros_entrypoint.sh
