/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Fri Mar 24 22:14:52 2023.
 */

#include <string.h>

#include "david.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int david_e_stop_pack(
    uint8_t *dst_p,
    const struct david_e_stop_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int david_e_stop_unpack(
    struct david_e_stop_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int david_e_start_pack(
    uint8_t *dst_p,
    const struct david_e_start_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int david_e_start_unpack(
    struct david_e_start_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int david_pitch_ctrl_home_pack(
    uint8_t *dst_p,
    const struct david_pitch_ctrl_home_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int david_pitch_ctrl_home_unpack(
    struct david_pitch_ctrl_home_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int david_set_trig_delay_pack(
    uint8_t *dst_p,
    const struct david_set_trig_delay_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->microseconds, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->microseconds, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->microseconds, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->microseconds, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->microseconds, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->microseconds, 40u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->max_count, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->max_count, 8u, 0xffu);

    return (8);
}

int david_set_trig_delay_unpack(
    struct david_set_trig_delay_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->microseconds = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->microseconds |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->microseconds |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->microseconds |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->microseconds |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->microseconds |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->max_count = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->max_count |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint64_t david_set_trig_delay_microseconds_encode(double value)
{
    return (uint64_t)(value);
}

double david_set_trig_delay_microseconds_decode(uint64_t value)
{
    return ((double)value);
}

bool david_set_trig_delay_microseconds_is_in_range(uint64_t value)
{
    return (value <= 281474976710655ull);
}

uint16_t david_set_trig_delay_max_count_encode(double value)
{
    return (uint16_t)(value);
}

double david_set_trig_delay_max_count_decode(uint16_t value)
{
    return ((double)value);
}

bool david_set_trig_delay_max_count_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int david_pitch_ctrl_left_pack(
    uint8_t *dst_p,
    const struct david_pitch_ctrl_left_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->count, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->count, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->count, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->count, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->count, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->count, 40u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->tolerance, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->tolerance, 8u, 0xffu);

    return (8);
}

int david_pitch_ctrl_left_unpack(
    struct david_pitch_ctrl_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->count = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->tolerance = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->tolerance |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint64_t david_pitch_ctrl_left_count_encode(double value)
{
    return (uint64_t)(value);
}

double david_pitch_ctrl_left_count_decode(uint64_t value)
{
    return ((double)value);
}

bool david_pitch_ctrl_left_count_is_in_range(uint64_t value)
{
    return (value <= 281474976710655ull);
}

uint16_t david_pitch_ctrl_left_tolerance_encode(double value)
{
    return (uint16_t)(value);
}

double david_pitch_ctrl_left_tolerance_decode(uint16_t value)
{
    return ((double)value);
}

bool david_pitch_ctrl_left_tolerance_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int david_pitch_ctrl_right_pack(
    uint8_t *dst_p,
    const struct david_pitch_ctrl_right_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->count, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->count, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->count, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->count, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->count, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->count, 40u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->tolerance, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->tolerance, 8u, 0xffu);

    return (8);
}

int david_pitch_ctrl_right_unpack(
    struct david_pitch_ctrl_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->count = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->tolerance = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->tolerance |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint64_t david_pitch_ctrl_right_count_encode(double value)
{
    return (uint64_t)(value);
}

double david_pitch_ctrl_right_count_decode(uint64_t value)
{
    return ((double)value);
}

bool david_pitch_ctrl_right_count_is_in_range(uint64_t value)
{
    return (value <= 281474976710655ull);
}

uint16_t david_pitch_ctrl_right_tolerance_encode(double value)
{
    return (uint16_t)(value);
}

double david_pitch_ctrl_right_tolerance_decode(uint16_t value)
{
    return ((double)value);
}

bool david_pitch_ctrl_right_tolerance_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int david_pitch_ctrl_both_pack(
    uint8_t *dst_p,
    const struct david_pitch_ctrl_both_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->count, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->count, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->count, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->count, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->count, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->count, 40u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->tolerance, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->tolerance, 8u, 0xffu);

    return (8);
}

int david_pitch_ctrl_both_unpack(
    struct david_pitch_ctrl_both_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->count = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->tolerance = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->tolerance |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint64_t david_pitch_ctrl_both_count_encode(double value)
{
    return (uint64_t)(value);
}

double david_pitch_ctrl_both_count_decode(uint64_t value)
{
    return ((double)value);
}

bool david_pitch_ctrl_both_count_is_in_range(uint64_t value)
{
    return (value <= 281474976710655ull);
}

uint16_t david_pitch_ctrl_both_tolerance_encode(double value)
{
    return (uint16_t)(value);
}

double david_pitch_ctrl_both_tolerance_decode(uint16_t value)
{
    return ((double)value);
}

bool david_pitch_ctrl_both_tolerance_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int david_pitch_telem_left_pack(
    uint8_t *dst_p,
    const struct david_pitch_telem_left_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u64(src_p->count, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->count, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->count, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->count, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->count, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->count, 40u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->done, 0u, 0x01u);

    return (7);
}

int david_pitch_telem_left_unpack(
    struct david_pitch_telem_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->count = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->done = unpack_right_shift_u8(src_p[6], 0u, 0x01u);

    return (0);
}

uint64_t david_pitch_telem_left_count_encode(double value)
{
    return (uint64_t)(value);
}

double david_pitch_telem_left_count_decode(uint64_t value)
{
    return ((double)value);
}

bool david_pitch_telem_left_count_is_in_range(uint64_t value)
{
    return (value <= 281474976710655ull);
}

uint8_t david_pitch_telem_left_done_encode(double value)
{
    return (uint8_t)(value);
}

double david_pitch_telem_left_done_decode(uint8_t value)
{
    return ((double)value);
}

bool david_pitch_telem_left_done_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int david_pitch_telem_right_pack(
    uint8_t *dst_p,
    const struct david_pitch_telem_right_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u64(src_p->count, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->count, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->count, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->count, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->count, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->count, 40u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->done, 0u, 0x01u);

    return (7);
}

int david_pitch_telem_right_unpack(
    struct david_pitch_telem_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->count = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->count |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->done = unpack_right_shift_u8(src_p[6], 0u, 0x01u);

    return (0);
}

uint64_t david_pitch_telem_right_count_encode(double value)
{
    return (uint64_t)(value);
}

double david_pitch_telem_right_count_decode(uint64_t value)
{
    return ((double)value);
}

bool david_pitch_telem_right_count_is_in_range(uint64_t value)
{
    return (value <= 281474976710655ull);
}

uint8_t david_pitch_telem_right_done_encode(double value)
{
    return (uint8_t)(value);
}

double david_pitch_telem_right_done_decode(uint8_t value)
{
    return ((double)value);
}

bool david_pitch_telem_right_done_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int david_loco_ctrl_left_pack(
    uint8_t *dst_p,
    const struct david_loco_ctrl_left_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u32(src_p->velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->velocity, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->velocity, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->velocity, 24u, 0xffu);

    return (4);
}

int david_loco_ctrl_left_unpack(
    struct david_loco_ctrl_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->velocity = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->velocity |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->velocity |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->velocity |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t david_loco_ctrl_left_velocity_encode(double value)
{
    return (uint32_t)(value);
}

double david_loco_ctrl_left_velocity_decode(uint32_t value)
{
    return ((double)value);
}

bool david_loco_ctrl_left_velocity_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int david_loco_ctrl_right_pack(
    uint8_t *dst_p,
    const struct david_loco_ctrl_right_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u32(src_p->velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->velocity, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->velocity, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->velocity, 24u, 0xffu);

    return (4);
}

int david_loco_ctrl_right_unpack(
    struct david_loco_ctrl_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->velocity = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->velocity |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->velocity |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->velocity |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t david_loco_ctrl_right_velocity_encode(double value)
{
    return (uint32_t)(value);
}

double david_loco_ctrl_right_velocity_decode(uint32_t value)
{
    return ((double)value);
}

bool david_loco_ctrl_right_velocity_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}
