// Input limits - auto generated from kcd

double PITCH_POSITION_TELEM_LEFT_POSITION_MIN =  -180.0;
double PITCH_POSITION_TELEM_LEFT_POSITION_MAX = 180;
double PITCH_POSITION_TELEM_RIGHT_POSITION_MIN =  -180.0;
double PITCH_POSITION_TELEM_RIGHT_POSITION_MAX = 180;
double PITCH_DRIVER_TELEM_LEFT_CURRENT_MIN =  0.0;
double PITCH_DRIVER_TELEM_LEFT_CURRENT_MAX = 20.0;
double PITCH_DRIVER_TELEM_RIGHT_CURRENT_MIN =  0.0;
double PITCH_DRIVER_TELEM_RIGHT_CURRENT_MAX = 20.0;
double PITCH_DRIVER_TELEM_LEFT_TEMPERATURE_MIN =  -40;
double PITCH_DRIVER_TELEM_LEFT_TEMPERATURE_MAX = 125;
double PITCH_DRIVER_TELEM_RIGHT_TEMPERATURE_MIN =  -40;
double PITCH_DRIVER_TELEM_RIGHT_TEMPERATURE_MAX = 125;
double LOCO_CTRL_LEFT_VEL_MIN =  -100;
double LOCO_CTRL_LEFT_VEL_MAX = 100;
double LOCO_CTRL_RIGHT_VEL_MIN =  -100;
double LOCO_CTRL_RIGHT_VEL_MAX = 100;
double EXCAV_CTRL_VEL_MIN =  -100;
double EXCAV_CTRL_VEL_MAX = 100;
double STEPPER_TELEM_LEFT_POSITION_MIN =  0.0;
double STEPPER_TELEM_LEFT_POSITION_MAX = 520;
double STEPPER_TELEM_RIGHT_POSITION_MIN =  0.0;
double STEPPER_TELEM_RIGHT_POSITION_MAX = 520;
double MAST_TELEM_ANGLE_MIN =  -360.5;
double MAST_TELEM_ANGLE_MAX = 360.5;
