# Docker compose file for operating cameras.
# If container fails with qt error try the following command
# xhost +local:root
services:
  ros:
    hostname: ros
    build: ../ros
    command: roscore
    volumes:
      - ../ros:/lunabotics/ros
    networks:
      - ros-docker-net
  cameras:
    hostname: cameras
    build: ../ros
    environment:
      - ROS_MASTER_URI=http://ros:11311
    command: /scripts/unfuck_realsense
    volumes:
      - /dev:/dev:rw
    networks:
      - ros-docker-net
    device_cgroup_rules:
      - c 81:* rmw
      - c 189:* rmw
  rviz:
    hostname: rviz
    build: ../ros
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros:11311
    command: rviz
    volumes:
      - /tmp:/tmp:rw
      - /dev/dri:/dev/dri:rw
    networks:
      - ros-docker-net
networks:
  ros-docker-net:
    name: "ros_docker_net"
