# Docker compose file for running the simulator on a dev machine.

services:
  ros:
    hostname: ros
    build: ../ros
    command: roscore
    volumes:
      - ../ros:/lunabotics/ros
    networks:
      - ros-docker-net
  webots:
    hostname: webots
    build: ../webots/docker
    environment:
      - ROS_MASTER_URI=http://ros:11311
      - DISPLAY
    command: webots /webots_worlds/gridmap_testbed.wbt
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
      - ../webots/worlds:/webots_worlds
    networks:
      - ros-docker-net
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
  rviz:
    hostname: rviz
    build: ../ros
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros:11311
    command: rviz
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
    networks:
      - ros-docker-net
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
networks:
  ros-docker-net:
    name: "ros_docker_net"
