// Generated by gencpp from file se2_grid_map_generator_msgs/AddCircularObstacleRequest.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDCIRCULAROBSTACLEREQUEST_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDCIRCULAROBSTACLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <se2_grid_map_generator_msgs/CircularObstacle.h>

namespace se2_grid_map_generator_msgs
{
template <class ContainerAllocator>
struct AddCircularObstacleRequest_
{
  typedef AddCircularObstacleRequest_<ContainerAllocator> Type;

  AddCircularObstacleRequest_()
    : obstacle()  {
    }
  AddCircularObstacleRequest_(const ContainerAllocator& _alloc)
    : obstacle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::se2_grid_map_generator_msgs::CircularObstacle_<ContainerAllocator>  _obstacle_type;
  _obstacle_type obstacle;





  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddCircularObstacleRequest_

typedef ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<std::allocator<void> > AddCircularObstacleRequest;

typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest > AddCircularObstacleRequestPtr;
typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest const> AddCircularObstacleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle == rhs.obstacle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_grid_map_generator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "439d75d797d3b32eca34874ea1d64d5d";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x439d75d797d3b32eULL;
  static const uint64_t static_value2 = 0xca34874ea1d64d5dULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/AddCircularObstacleRequest";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"se2_grid_map_generator_msgs/CircularObstacle obstacle\n"
"\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/CircularObstacle\n"
"se2_grid_map_generator_msgs/Circle2D circle\n"
"std_msgs/String[] layers\n"
"std_msgs/Float64[] values\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/Circle2D\n"
"se2_grid_map_generator_msgs/Position2D center\n"
"std_msgs/Float64 radius\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/Position2D\n"
"std_msgs/Float64 x\n"
"std_msgs/Float64 y\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddCircularObstacleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_grid_map_generator_msgs::AddCircularObstacleRequest_<ContainerAllocator>& v)
  {
    s << indent << "obstacle: ";
    s << std::endl;
    Printer< ::se2_grid_map_generator_msgs::CircularObstacle_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDCIRCULAROBSTACLEREQUEST_H
