// Generated by gencpp from file se2_grid_map_generator_msgs/AddNan.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDNAN_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDNAN_H

#include <ros/service_traits.h>


#include <se2_grid_map_generator_msgs/AddNanRequest.h>
#include <se2_grid_map_generator_msgs/AddNanResponse.h>


namespace se2_grid_map_generator_msgs
{

struct AddNan
{

typedef AddNanRequest Request;
typedef AddNanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddNan
} // namespace se2_grid_map_generator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::AddNan > {
  static const char* value()
  {
    return "ed846c130da1159d54d0e3b43ecc2916";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddNan&) { return value(); }
};

template<>
struct DataType< ::se2_grid_map_generator_msgs::AddNan > {
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/AddNan";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddNan&) { return value(); }
};


// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::AddNanRequest> should match
// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::AddNan >
template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::AddNanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::se2_grid_map_generator_msgs::AddNan >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::AddNanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_grid_map_generator_msgs::AddNanRequest> should match
// service_traits::DataType< ::se2_grid_map_generator_msgs::AddNan >
template<>
struct DataType< ::se2_grid_map_generator_msgs::AddNanRequest>
{
  static const char* value()
  {
    return DataType< ::se2_grid_map_generator_msgs::AddNan >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::AddNanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::AddNanResponse> should match
// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::AddNan >
template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::AddNanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::se2_grid_map_generator_msgs::AddNan >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::AddNanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_grid_map_generator_msgs::AddNanResponse> should match
// service_traits::DataType< ::se2_grid_map_generator_msgs::AddNan >
template<>
struct DataType< ::se2_grid_map_generator_msgs::AddNanResponse>
{
  static const char* value()
  {
    return DataType< ::se2_grid_map_generator_msgs::AddNan >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::AddNanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDNAN_H
