// Generated by gencpp from file se2_grid_map_generator_msgs/AddPolygonObstacle.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDPOLYGONOBSTACLE_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDPOLYGONOBSTACLE_H

#include <ros/service_traits.h>


#include <se2_grid_map_generator_msgs/AddPolygonObstacleRequest.h>
#include <se2_grid_map_generator_msgs/AddPolygonObstacleResponse.h>


namespace se2_grid_map_generator_msgs
{

struct AddPolygonObstacle
{

typedef AddPolygonObstacleRequest Request;
typedef AddPolygonObstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddPolygonObstacle
} // namespace se2_grid_map_generator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacle > {
  static const char* value()
  {
    return "8cdfa34c81ded8fbfe0b3c21eb0b43e9";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacle&) { return value(); }
};

template<>
struct DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacle > {
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/AddPolygonObstacle";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacle&) { return value(); }
};


// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest> should match
// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacle >
template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacle >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest> should match
// service_traits::DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacle >
template<>
struct DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest>
{
  static const char* value()
  {
    return DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacle >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacleResponse> should match
// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacle >
template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacle >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacleResponse> should match
// service_traits::DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacle >
template<>
struct DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacleResponse>
{
  static const char* value()
  {
    return DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacle >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDPOLYGONOBSTACLE_H
