// Generated by gencpp from file se2_grid_map_generator_msgs/AddPolygonObstacleRequest.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDPOLYGONOBSTACLEREQUEST_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDPOLYGONOBSTACLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <se2_grid_map_generator_msgs/PolygonObstacle.h>

namespace se2_grid_map_generator_msgs
{
template <class ContainerAllocator>
struct AddPolygonObstacleRequest_
{
  typedef AddPolygonObstacleRequest_<ContainerAllocator> Type;

  AddPolygonObstacleRequest_()
    : obstacle()  {
    }
  AddPolygonObstacleRequest_(const ContainerAllocator& _alloc)
    : obstacle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::se2_grid_map_generator_msgs::PolygonObstacle_<ContainerAllocator>  _obstacle_type;
  _obstacle_type obstacle;





  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddPolygonObstacleRequest_

typedef ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<std::allocator<void> > AddPolygonObstacleRequest;

typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest > AddPolygonObstacleRequestPtr;
typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest const> AddPolygonObstacleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle == rhs.obstacle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_grid_map_generator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa762edd6cdbe7dacb2bbde47c7da09b";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa762edd6cdbe7daULL;
  static const uint64_t static_value2 = 0xcb2bbde47c7da09bULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/AddPolygonObstacleRequest";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"se2_grid_map_generator_msgs/PolygonObstacle obstacle\n"
"\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/PolygonObstacle\n"
"se2_grid_map_generator_msgs/Polygon2D polygon\n"
"std_msgs/String[] layers\n"
"std_msgs/Float64[] values\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/Polygon2D\n"
"se2_grid_map_generator_msgs/Position2D[] vertices\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/Position2D\n"
"std_msgs/Float64 x\n"
"std_msgs/Float64 y\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddPolygonObstacleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_grid_map_generator_msgs::AddPolygonObstacleRequest_<ContainerAllocator>& v)
  {
    s << indent << "obstacle: ";
    s << std::endl;
    Printer< ::se2_grid_map_generator_msgs::PolygonObstacle_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_ADDPOLYGONOBSTACLEREQUEST_H
