// Generated by gencpp from file se2_grid_map_generator_msgs/Circle2D.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_CIRCLE2D_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_CIRCLE2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <se2_grid_map_generator_msgs/Position2D.h>
#include <std_msgs/Float64.h>

namespace se2_grid_map_generator_msgs
{
template <class ContainerAllocator>
struct Circle2D_
{
  typedef Circle2D_<ContainerAllocator> Type;

  Circle2D_()
    : center()
    , radius()  {
    }
  Circle2D_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , radius(_alloc)  {
  (void)_alloc;
    }



   typedef  ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> const> ConstPtr;

}; // struct Circle2D_

typedef ::se2_grid_map_generator_msgs::Circle2D_<std::allocator<void> > Circle2D;

typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Circle2D > Circle2DPtr;
typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Circle2D const> Circle2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_grid_map_generator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dfece0138cac79dd8ef38f9d1fa9947";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dfece0138cac79dULL;
  static const uint64_t static_value2 = 0xd8ef38f9d1fa9947ULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/Circle2D";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/Position2D center\n"
"std_msgs/Float64 radius\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/Position2D\n"
"std_msgs/Float64 x\n"
"std_msgs/Float64 y\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Circle2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_grid_map_generator_msgs::Circle2D_<ContainerAllocator>& v)
  {
    s << indent << "center: ";
    s << std::endl;
    Printer< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "radius: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_CIRCLE2D_H
