// Generated by gencpp from file se2_grid_map_generator_msgs/Polygon2D.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_POLYGON2D_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_POLYGON2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <se2_grid_map_generator_msgs/Position2D.h>

namespace se2_grid_map_generator_msgs
{
template <class ContainerAllocator>
struct Polygon2D_
{
  typedef Polygon2D_<ContainerAllocator> Type;

  Polygon2D_()
    : vertices()  {
    }
  Polygon2D_(const ContainerAllocator& _alloc)
    : vertices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >> _vertices_type;
  _vertices_type vertices;





  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> const> ConstPtr;

}; // struct Polygon2D_

typedef ::se2_grid_map_generator_msgs::Polygon2D_<std::allocator<void> > Polygon2D;

typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Polygon2D > Polygon2DPtr;
typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Polygon2D const> Polygon2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator2> & rhs)
{
  return lhs.vertices == rhs.vertices;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_grid_map_generator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bccfee9dbb3170a57e32edc6d3cfcef5";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbccfee9dbb3170a5ULL;
  static const uint64_t static_value2 = 0x7e32edc6d3cfcef5ULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/Polygon2D";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/Position2D[] vertices\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/Position2D\n"
"std_msgs/Float64 x\n"
"std_msgs/Float64 y\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vertices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Polygon2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_grid_map_generator_msgs::Polygon2D_<ContainerAllocator>& v)
  {
    s << indent << "vertices[]" << std::endl;
    for (size_t i = 0; i < v.vertices.size(); ++i)
    {
      s << indent << "  vertices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >::stream(s, indent + "    ", v.vertices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_POLYGON2D_H
