// Generated by gencpp from file se2_grid_map_generator_msgs/Position2D.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_POSITION2D_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_POSITION2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace se2_grid_map_generator_msgs
{
template <class ContainerAllocator>
struct Position2D_
{
  typedef Position2D_<ContainerAllocator> Type;

  Position2D_()
    : x()
    , y()  {
    }
  Position2D_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> const> ConstPtr;

}; // struct Position2D_

typedef ::se2_grid_map_generator_msgs::Position2D_<std::allocator<void> > Position2D;

typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Position2D > Position2DPtr;
typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::Position2D const> Position2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_grid_map_generator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5507085553fb157248c9d5a62e2bae14";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5507085553fb1572ULL;
  static const uint64_t static_value2 = 0x48c9d5a62e2bae14ULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/Position2D";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64 x\n"
"std_msgs/Float64 y\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_POSITION2D_H
