// Generated by gencpp from file se2_grid_map_generator_msgs/SetUniformValueRequest.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_SETUNIFORMVALUEREQUEST_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_SETUNIFORMVALUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/Float64.h>

namespace se2_grid_map_generator_msgs
{
template <class ContainerAllocator>
struct SetUniformValueRequest_
{
  typedef SetUniformValueRequest_<ContainerAllocator> Type;

  SetUniformValueRequest_()
    : layers()
    , values()  {
    }
  SetUniformValueRequest_(const ContainerAllocator& _alloc)
    : layers(_alloc)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::String_<ContainerAllocator> >> _layers_type;
  _layers_type layers;

   typedef std::vector< ::std_msgs::Float64_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::Float64_<ContainerAllocator> >> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetUniformValueRequest_

typedef ::se2_grid_map_generator_msgs::SetUniformValueRequest_<std::allocator<void> > SetUniformValueRequest;

typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::SetUniformValueRequest > SetUniformValueRequestPtr;
typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::SetUniformValueRequest const> SetUniformValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.layers == rhs.layers &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_grid_map_generator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4670bceb1fea55bf0df1cc8795202181";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4670bceb1fea55bfULL;
  static const uint64_t static_value2 = 0x0df1cc8795202181ULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/SetUniformValueRequest";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"std_msgs/String[] layers\n"
"std_msgs/Float64[] values\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.layers);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetUniformValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_grid_map_generator_msgs::SetUniformValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "layers[]" << std::endl;
    for (size_t i = 0; i < v.layers.size(); ++i)
    {
      s << indent << "  layers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.layers[i]);
    }
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "    ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_SETUNIFORMVALUEREQUEST_H
