// Generated by gencpp from file se2_grid_map_generator_msgs/UpdateMapPositionRequest.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_UPDATEMAPPOSITIONREQUEST_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_UPDATEMAPPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <se2_grid_map_generator_msgs/Position2D.h>

namespace se2_grid_map_generator_msgs
{
template <class ContainerAllocator>
struct UpdateMapPositionRequest_
{
  typedef UpdateMapPositionRequest_<ContainerAllocator> Type;

  UpdateMapPositionRequest_()
    : position()  {
    }
  UpdateMapPositionRequest_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateMapPositionRequest_

typedef ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<std::allocator<void> > UpdateMapPositionRequest;

typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest > UpdateMapPositionRequestPtr;
typedef boost::shared_ptr< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest const> UpdateMapPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator1> & lhs, const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_grid_map_generator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a3d0c982d9fc216ac402cd9c440f775";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a3d0c982d9fc216ULL;
  static const uint64_t static_value2 = 0xac402cd9c440f775ULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/UpdateMapPositionRequest";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"se2_grid_map_generator_msgs/Position2D position\n"
"\n"
"================================================================================\n"
"MSG: se2_grid_map_generator_msgs/Position2D\n"
"std_msgs/Float64 x\n"
"std_msgs/Float64 y\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateMapPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::se2_grid_map_generator_msgs::Position2D_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_UPDATEMAPPOSITIONREQUEST_H
