// Generated by gencpp from file se2_grid_map_generator_msgs/UpdateMapPosition.msg
// DO NOT EDIT!


#ifndef SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_UPDATEMAPPOSITION_H
#define SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_UPDATEMAPPOSITION_H

#include <ros/service_traits.h>


#include <se2_grid_map_generator_msgs/UpdateMapPositionRequest.h>
#include <se2_grid_map_generator_msgs/UpdateMapPositionResponse.h>


namespace se2_grid_map_generator_msgs
{

struct UpdateMapPosition
{

typedef UpdateMapPositionRequest Request;
typedef UpdateMapPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateMapPosition
} // namespace se2_grid_map_generator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPosition > {
  static const char* value()
  {
    return "ce04429a523a22c93100dc2950508e3d";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPosition&) { return value(); }
};

template<>
struct DataType< ::se2_grid_map_generator_msgs::UpdateMapPosition > {
  static const char* value()
  {
    return "se2_grid_map_generator_msgs/UpdateMapPosition";
  }

  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPosition&) { return value(); }
};


// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest> should match
// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPosition >
template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPosition >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest> should match
// service_traits::DataType< ::se2_grid_map_generator_msgs::UpdateMapPosition >
template<>
struct DataType< ::se2_grid_map_generator_msgs::UpdateMapPositionRequest>
{
  static const char* value()
  {
    return DataType< ::se2_grid_map_generator_msgs::UpdateMapPosition >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPositionResponse> should match
// service_traits::MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPosition >
template<>
struct MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::se2_grid_map_generator_msgs::UpdateMapPosition >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_grid_map_generator_msgs::UpdateMapPositionResponse> should match
// service_traits::DataType< ::se2_grid_map_generator_msgs::UpdateMapPosition >
template<>
struct DataType< ::se2_grid_map_generator_msgs::UpdateMapPositionResponse>
{
  static const char* value()
  {
    return DataType< ::se2_grid_map_generator_msgs::UpdateMapPosition >::value();
  }
  static const char* value(const ::se2_grid_map_generator_msgs::UpdateMapPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SE2_GRID_MAP_GENERATOR_MSGS_MESSAGE_UPDATEMAPPOSITION_H
