// Generated by gencpp from file se2_navigation_msgs/PathRequestMsg.msg
// DO NOT EDIT!


#ifndef SE2_NAVIGATION_MSGS_MESSAGE_PATHREQUESTMSG_H
#define SE2_NAVIGATION_MSGS_MESSAGE_PATHREQUESTMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace se2_navigation_msgs
{
template <class ContainerAllocator>
struct PathRequestMsg_
{
  typedef PathRequestMsg_<ContainerAllocator> Type;

  PathRequestMsg_()
    : startingPose()
    , goalPose()  {
    }
  PathRequestMsg_(const ContainerAllocator& _alloc)
    : startingPose(_alloc)
    , goalPose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _startingPose_type;
  _startingPose_type startingPose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goalPose_type;
  _goalPose_type goalPose;





  typedef boost::shared_ptr< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> const> ConstPtr;

}; // struct PathRequestMsg_

typedef ::se2_navigation_msgs::PathRequestMsg_<std::allocator<void> > PathRequestMsg;

typedef boost::shared_ptr< ::se2_navigation_msgs::PathRequestMsg > PathRequestMsgPtr;
typedef boost::shared_ptr< ::se2_navigation_msgs::PathRequestMsg const> PathRequestMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator1> & lhs, const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator2> & rhs)
{
  return lhs.startingPose == rhs.startingPose &&
    lhs.goalPose == rhs.goalPose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator1> & lhs, const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_navigation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0af408eeb123474bf9e677b140defe0";
  }

  static const char* value(const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0af408eeb123474ULL;
  static const uint64_t static_value2 = 0xbf9e677b140defe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_navigation_msgs/PathRequestMsg";
  }

  static const char* value(const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose startingPose\n"
"geometry_msgs/Pose goalPose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.startingPose);
      stream.next(m.goalPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathRequestMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator>& v)
  {
    s << indent << "startingPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.startingPose);
    s << indent << "goalPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goalPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_NAVIGATION_MSGS_MESSAGE_PATHREQUESTMSG_H
