// Generated by gencpp from file se2_navigation_msgs/RequestPathSrvRequest.msg
// DO NOT EDIT!


#ifndef SE2_NAVIGATION_MSGS_MESSAGE_REQUESTPATHSRVREQUEST_H
#define SE2_NAVIGATION_MSGS_MESSAGE_REQUESTPATHSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <se2_navigation_msgs/PathRequestMsg.h>

namespace se2_navigation_msgs
{
template <class ContainerAllocator>
struct RequestPathSrvRequest_
{
  typedef RequestPathSrvRequest_<ContainerAllocator> Type;

  RequestPathSrvRequest_()
    : pathRequest()  {
    }
  RequestPathSrvRequest_(const ContainerAllocator& _alloc)
    : pathRequest(_alloc)  {
  (void)_alloc;
    }



   typedef  ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator>  _pathRequest_type;
  _pathRequest_type pathRequest;





  typedef boost::shared_ptr< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestPathSrvRequest_

typedef ::se2_navigation_msgs::RequestPathSrvRequest_<std::allocator<void> > RequestPathSrvRequest;

typedef boost::shared_ptr< ::se2_navigation_msgs::RequestPathSrvRequest > RequestPathSrvRequestPtr;
typedef boost::shared_ptr< ::se2_navigation_msgs::RequestPathSrvRequest const> RequestPathSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator1> & lhs, const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pathRequest == rhs.pathRequest;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator1> & lhs, const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace se2_navigation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db2b254db8276cf2c8fcea29d6fee192";
  }

  static const char* value(const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb2b254db8276cf2ULL;
  static const uint64_t static_value2 = 0xc8fcea29d6fee192ULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_navigation_msgs/RequestPathSrvRequest";
  }

  static const char* value(const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"PathRequestMsg 		pathRequest                          # Query, maybe useful for the future\n"
"\n"
"================================================================================\n"
"MSG: se2_navigation_msgs/PathRequestMsg\n"
"geometry_msgs/Pose startingPose\n"
"geometry_msgs/Pose goalPose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pathRequest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestPathSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se2_navigation_msgs::RequestPathSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "pathRequest: ";
    s << std::endl;
    Printer< ::se2_navigation_msgs::PathRequestMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.pathRequest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE2_NAVIGATION_MSGS_MESSAGE_REQUESTPATHSRVREQUEST_H
