// Generated by gencpp from file se2_navigation_msgs/RequestCurrentStateSrvRequest.msg
// DO NOT EDIT!


#ifndef SE2_NAVIGATION_MSGS_MESSAGE_REQUESTCURRENTSTATESRVREQUEST_H
#define SE2_NAVIGATION_MSGS_MESSAGE_REQUESTCURRENTSTATESRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace se2_navigation_msgs
{
template <class ContainerAllocator>
struct RequestCurrentStateSrvRequest_
{
  typedef RequestCurrentStateSrvRequest_<ContainerAllocator> Type;

  RequestCurrentStateSrvRequest_()
    {
    }
  RequestCurrentStateSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestCurrentStateSrvRequest_

typedef ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<std::allocator<void> > RequestCurrentStateSrvRequest;

typedef boost::shared_ptr< ::se2_navigation_msgs::RequestCurrentStateSrvRequest > RequestCurrentStateSrvRequestPtr;
typedef boost::shared_ptr< ::se2_navigation_msgs::RequestCurrentStateSrvRequest const> RequestCurrentStateSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace se2_navigation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se2_navigation_msgs/RequestCurrentStateSrvRequest";
  }

  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
;
  }

  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestCurrentStateSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::se2_navigation_msgs::RequestCurrentStateSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SE2_NAVIGATION_MSGS_MESSAGE_REQUESTCURRENTSTATESRVREQUEST_H
