// Generated by gencpp from file se2_navigation_msgs/RequestCurrentStateSrv.msg
// DO NOT EDIT!


#ifndef SE2_NAVIGATION_MSGS_MESSAGE_REQUESTCURRENTSTATESRV_H
#define SE2_NAVIGATION_MSGS_MESSAGE_REQUESTCURRENTSTATESRV_H

#include <ros/service_traits.h>


#include <se2_navigation_msgs/RequestCurrentStateSrvRequest.h>
#include <se2_navigation_msgs/RequestCurrentStateSrvResponse.h>


namespace se2_navigation_msgs
{

struct RequestCurrentStateSrv
{

typedef RequestCurrentStateSrvRequest Request;
typedef RequestCurrentStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestCurrentStateSrv
} // namespace se2_navigation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrv > {
  static const char* value()
  {
    return "c79f0d88a7597db980a56d7ac144c654";
  }

  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrv&) { return value(); }
};

template<>
struct DataType< ::se2_navigation_msgs::RequestCurrentStateSrv > {
  static const char* value()
  {
    return "se2_navigation_msgs/RequestCurrentStateSrv";
  }

  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrvRequest> should match
// service_traits::MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrv >
template<>
struct MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrv >::value();
  }
  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_navigation_msgs::RequestCurrentStateSrvRequest> should match
// service_traits::DataType< ::se2_navigation_msgs::RequestCurrentStateSrv >
template<>
struct DataType< ::se2_navigation_msgs::RequestCurrentStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::se2_navigation_msgs::RequestCurrentStateSrv >::value();
  }
  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrvResponse> should match
// service_traits::MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrv >
template<>
struct MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::se2_navigation_msgs::RequestCurrentStateSrv >::value();
  }
  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_navigation_msgs::RequestCurrentStateSrvResponse> should match
// service_traits::DataType< ::se2_navigation_msgs::RequestCurrentStateSrv >
template<>
struct DataType< ::se2_navigation_msgs::RequestCurrentStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::se2_navigation_msgs::RequestCurrentStateSrv >::value();
  }
  static const char* value(const ::se2_navigation_msgs::RequestCurrentStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SE2_NAVIGATION_MSGS_MESSAGE_REQUESTCURRENTSTATESRV_H
