// Generated by gencpp from file se2_navigation_msgs/SendControllerCommandSrv.msg
// DO NOT EDIT!


#ifndef SE2_NAVIGATION_MSGS_MESSAGE_SENDCONTROLLERCOMMANDSRV_H
#define SE2_NAVIGATION_MSGS_MESSAGE_SENDCONTROLLERCOMMANDSRV_H

#include <ros/service_traits.h>


#include <se2_navigation_msgs/SendControllerCommandSrvRequest.h>
#include <se2_navigation_msgs/SendControllerCommandSrvResponse.h>


namespace se2_navigation_msgs
{

struct SendControllerCommandSrv
{

typedef SendControllerCommandSrvRequest Request;
typedef SendControllerCommandSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendControllerCommandSrv
} // namespace se2_navigation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrv > {
  static const char* value()
  {
    return "8f41fa61e7f9b864f313c51bd6bcb1ba";
  }

  static const char* value(const ::se2_navigation_msgs::SendControllerCommandSrv&) { return value(); }
};

template<>
struct DataType< ::se2_navigation_msgs::SendControllerCommandSrv > {
  static const char* value()
  {
    return "se2_navigation_msgs/SendControllerCommandSrv";
  }

  static const char* value(const ::se2_navigation_msgs::SendControllerCommandSrv&) { return value(); }
};


// service_traits::MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrvRequest> should match
// service_traits::MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrv >
template<>
struct MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrv >::value();
  }
  static const char* value(const ::se2_navigation_msgs::SendControllerCommandSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_navigation_msgs::SendControllerCommandSrvRequest> should match
// service_traits::DataType< ::se2_navigation_msgs::SendControllerCommandSrv >
template<>
struct DataType< ::se2_navigation_msgs::SendControllerCommandSrvRequest>
{
  static const char* value()
  {
    return DataType< ::se2_navigation_msgs::SendControllerCommandSrv >::value();
  }
  static const char* value(const ::se2_navigation_msgs::SendControllerCommandSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrvResponse> should match
// service_traits::MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrv >
template<>
struct MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::se2_navigation_msgs::SendControllerCommandSrv >::value();
  }
  static const char* value(const ::se2_navigation_msgs::SendControllerCommandSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::se2_navigation_msgs::SendControllerCommandSrvResponse> should match
// service_traits::DataType< ::se2_navigation_msgs::SendControllerCommandSrv >
template<>
struct DataType< ::se2_navigation_msgs::SendControllerCommandSrvResponse>
{
  static const char* value()
  {
    return DataType< ::se2_navigation_msgs::SendControllerCommandSrv >::value();
  }
  static const char* value(const ::se2_navigation_msgs::SendControllerCommandSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SE2_NAVIGATION_MSGS_MESSAGE_SENDCONTROLLERCOMMANDSRV_H
