#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Generates a shell inside the ROS container.

DIR="$(realpath "$(dirname "$0")")"/..

sudo docker build "$DIR/ros" -t lunabotics-2023-ros

echo "Xbox Controller? (y/n):"
read yn

# On Jetson and laptop (change IP to match)
# ROS_MASTER_URI=http://129.138.170.202:11311
# On Jetson
# ROS_IP=129.138.170.202
# On Laptop
# ROS_IP=laptop ip

if [ "$yn" = "y" ]; then
    sudo docker run \
        --rm \
        -it \
        --net=host \
        --device=/dev/input/js0 \
        -v $DIR:$DIR \
        -e DISPLAY \
        -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
        -v /dev:/dev:rw \
        --device-cgroup-rule "c 81:* rmw" \
        --device-cgroup-rule "c 189:* rmw" \
        lunabotics-2023-ros \
        sh -c "
            cd $PWD
            export HOME="$HOME"
            export PS1='\u@\h:\w\$ '
            [ -e $DIR/ros/catkin_ws/devel/setup.sh ] && . $DIR/ros/catkin_ws/devel/setup.sh
            bash
            "
else
    sudo docker run \
        --rm \
        -it \
        --net=host \
        -v $DIR:$DIR \
        -e DISPLAY \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /dev:/dev \
        lunabotics-2023-ros \
        sh -c "
            cd $PWD
            export HOME="$HOME"
            export PS1='\u@\h:\w\$ '
            [ -e $DIR/ros/catkin_ws/devel/setup.sh ] && . $DIR/ros/catkin_ws/devel/setup.sh
            bash
            "
fi


# ROS might create files owned by root here; it'll cause all kinds of
# problems with git.
sudo chown -R "$(id -u):$(id -g)" "$DIR"
