#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")

IP=172.23.0.4

docker run \
       --volume $PWD/../ros:/lunabotics/ros \
       --net=containers_default \
       --env="ROS_MASTER_URI=http://172.23.0.2:11311" \
       --env="ROS_IP=$IP:11311" \
       --ip="$IP" \
       -it \
       containers-webots \
       /bin/bash
