#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")

IP=172.23.0.4

docker run \
       --volume $PWD/../ros:/lunabotics/ros \
       --net=ros_docker_net \
       --env="ROS_MASTER_URI=http://ros:11311" \
       -it \
       webots_ros \
       /bin/bash
