#!/usr/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")

docker run \
       --volume $PWD/../ros:/lunabotics/ros \
       --net=ros_docker_net \
       --env="ROS_MASTER_URI=http://ros:11311" \
       -it \
       webots_ros \
       sh -c "
              rosservice call /david_sim/Velodyne_Puck/enable 32
              rosservice call /david_sim/Velodyne_Puck/enable_point_cloud true
              rosrun tf2_ros static_transform_publisher 0 0 0 0 0 0 /map /david_sim/Velodyne_Puck
             "
