#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

xhost +local:root

cd "$(dirname "$0")/../containers"
if which docker-compose 2>/dev/null; then
    sudo docker-compose -f simulator.yml up
else
    sudo docker compose -f simulator.yml up
fi
