#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Generates a shell inside the ROS container, with ROS_MASTER_URI set
# to the Jetson.

JETSON_ADDRESS=129.138.173.40
MY_ADDRESS=$(ip route get $JETSON_ADDRESS | sed 's/.* src //;s/ .*//;2,$d')

DIR="$(realpath "$(dirname "$0")")"/..

sudo docker build "$DIR/ros" -t lunabotics-2023-ros
sudo docker run \
     --rm \
     -it \
     -v $DIR:$DIR \
     -e DISPLAY \
     -e ROS_IP=$MY_ADDRESS \
     -v /tmp/.X11-unix:/tmp/.X11-unix \
     -v /dev/dri:/dev/dri \
     --network=host \
     lunabotics-2023-ros \
     sh -c "
         cd $PWD
         export HOME="$HOME"
         export PS1='\u@\h:\w\$ '
         [ -e $DIR/ros/catkin_ws/devel/setup.sh ] && . $DIR/ros/catkin_ws/devel/setup.sh
         export ROS_MASTER_URI='http://$JETSON_ADDRESS:11311'
         bash
     "

# ROS might create files owned by root here; it'll cause all kinds of
# problems with git.
sudo chown -R "$(id -u):$(id -g)" "$DIR"
