FROM ros:noetic-ros-core

RUN apt-get update -y

# Standard tools
RUN apt-get install -y clang make gcc g++ inetutils-ping net-tools git tmux

# 2. Install ROS packages from apt.
RUN apt-get install -y \
    ros-noetic-move-base \
    ros-noetic-rviz \
    ros-noetic-rosmon \
    ros-noetic-tf2-tools \
    ros-noetic-robot-state-publisher \
    ros-noetic-joint-state-publisher \
    ros-noetic-realsense2-camera \
    ros-noetic-ompl \
    ros-noetic-grid-map-core \
    ros-noetic-grid-map-ros \
    ros-noetic-eigen-conversions \
    ros-noetic-gazebo-ros 
    

COPY scripts /scripts
# COPY catkin_ws /catkin_ws
COPY catkin_ws/.catkin_workspace /catkin_ws/.catkin_workspace
# COPY catkin_ws/src/CMakeLists.txt /catkin_ws/src/CMakeLists.txt
COPY catkin_ws/src/david_tui /catkin_ws/src/david_tui
COPY catkin_ws/src/motor_bridge /catkin_ws/src/motor_bridge

RUN cd /catkin_ws && \
    rm -rf /catkin_ws/build /catkin_ws/devel && \
    /ros_entrypoint.sh catkin_make

# Add /catkin_ws to the ROS environment.
COPY ros_entrypoint.sh /ros_entrypoint.sh
