// Generated by gencpp from file motor_bridge/Digger.msg
// DO NOT EDIT!


#ifndef MOTOR_BRIDGE_MESSAGE_DIGGER_H
#define MOTOR_BRIDGE_MESSAGE_DIGGER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_bridge
{
template <class ContainerAllocator>
struct Digger_
{
  typedef Digger_<ContainerAllocator> Type;

  Digger_()
    : speed(0)  {
    }
  Digger_(const ContainerAllocator& _alloc)
    : speed(0)  {
  (void)_alloc;
    }



   typedef int32_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::motor_bridge::Digger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_bridge::Digger_<ContainerAllocator> const> ConstPtr;

}; // struct Digger_

typedef ::motor_bridge::Digger_<std::allocator<void> > Digger;

typedef boost::shared_ptr< ::motor_bridge::Digger > DiggerPtr;
typedef boost::shared_ptr< ::motor_bridge::Digger const> DiggerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_bridge::Digger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_bridge::Digger_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_bridge::Digger_<ContainerAllocator1> & lhs, const ::motor_bridge::Digger_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_bridge::Digger_<ContainerAllocator1> & lhs, const ::motor_bridge::Digger_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_bridge::Digger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_bridge::Digger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_bridge::Digger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_bridge::Digger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_bridge::Digger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_bridge::Digger_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_bridge::Digger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f7a812be2def1e9db804a7fbea8c3a5";
  }

  static const char* value(const ::motor_bridge::Digger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f7a812be2def1e9ULL;
  static const uint64_t static_value2 = 0xdb804a7fbea8c3a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_bridge::Digger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_bridge/Digger";
  }

  static const char* value(const ::motor_bridge::Digger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_bridge::Digger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Digger Control Message\n"
"\n"
"# Speed Control (Full Backward = -1024, Stop = 0, Full Forward = 1024)\n"
"int32 speed\n"
"\n"
;
  }

  static const char* value(const ::motor_bridge::Digger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_bridge::Digger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Digger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_bridge::Digger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_bridge::Digger_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_BRIDGE_MESSAGE_DIGGER_H
