# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from se2_grid_map_generator_msgs/Polygon2D.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import se2_grid_map_generator_msgs.msg
import std_msgs.msg

class Polygon2D(genpy.Message):
  _md5sum = "bccfee9dbb3170a57e32edc6d3cfcef5"
  _type = "se2_grid_map_generator_msgs/Polygon2D"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """se2_grid_map_generator_msgs/Position2D[] vertices
================================================================================
MSG: se2_grid_map_generator_msgs/Position2D
std_msgs/Float64 x
std_msgs/Float64 y
================================================================================
MSG: std_msgs/Float64
float64 data"""
  __slots__ = ['vertices']
  _slot_types = ['se2_grid_map_generator_msgs/Position2D[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vertices

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Polygon2D, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vertices is None:
        self.vertices = []
    else:
      self.vertices = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.vertices)
      buff.write(_struct_I.pack(length))
      for val1 in self.vertices:
        _v1 = val1.x
        _x = _v1.data
        buff.write(_get_struct_d().pack(_x))
        _v2 = val1.y
        _x = _v2.data
        buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vertices is None:
        self.vertices = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.vertices = []
      for i in range(0, length):
        val1 = se2_grid_map_generator_msgs.msg.Position2D()
        _v3 = val1.x
        start = end
        end += 8
        (_v3.data,) = _get_struct_d().unpack(str[start:end])
        _v4 = val1.y
        start = end
        end += 8
        (_v4.data,) = _get_struct_d().unpack(str[start:end])
        self.vertices.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.vertices)
      buff.write(_struct_I.pack(length))
      for val1 in self.vertices:
        _v5 = val1.x
        _x = _v5.data
        buff.write(_get_struct_d().pack(_x))
        _v6 = val1.y
        _x = _v6.data
        buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vertices is None:
        self.vertices = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.vertices = []
      for i in range(0, length):
        val1 = se2_grid_map_generator_msgs.msg.Position2D()
        _v7 = val1.x
        start = end
        end += 8
        (_v7.data,) = _get_struct_d().unpack(str[start:end])
        _v8 = val1.y
        start = end
        end += 8
        (_v8.data,) = _get_struct_d().unpack(str[start:end])
        self.vertices.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
