# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from se2_navigation_msgs/RequestPathSrvRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import se2_navigation_msgs.msg

class RequestPathSrvRequest(genpy.Message):
  _md5sum = "db2b254db8276cf2c8fcea29d6fee192"
  _type = "se2_navigation_msgs/RequestPathSrvRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Request
PathRequestMsg 		pathRequest                          # Query, maybe useful for the future

================================================================================
MSG: se2_navigation_msgs/PathRequestMsg
geometry_msgs/Pose startingPose
geometry_msgs/Pose goalPose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['pathRequest']
  _slot_types = ['se2_navigation_msgs/PathRequestMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pathRequest

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RequestPathSrvRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pathRequest is None:
        self.pathRequest = se2_navigation_msgs.msg.PathRequestMsg()
    else:
      self.pathRequest = se2_navigation_msgs.msg.PathRequestMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_14d().pack(_x.pathRequest.startingPose.position.x, _x.pathRequest.startingPose.position.y, _x.pathRequest.startingPose.position.z, _x.pathRequest.startingPose.orientation.x, _x.pathRequest.startingPose.orientation.y, _x.pathRequest.startingPose.orientation.z, _x.pathRequest.startingPose.orientation.w, _x.pathRequest.goalPose.position.x, _x.pathRequest.goalPose.position.y, _x.pathRequest.goalPose.position.z, _x.pathRequest.goalPose.orientation.x, _x.pathRequest.goalPose.orientation.y, _x.pathRequest.goalPose.orientation.z, _x.pathRequest.goalPose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pathRequest is None:
        self.pathRequest = se2_navigation_msgs.msg.PathRequestMsg()
      end = 0
      _x = self
      start = end
      end += 112
      (_x.pathRequest.startingPose.position.x, _x.pathRequest.startingPose.position.y, _x.pathRequest.startingPose.position.z, _x.pathRequest.startingPose.orientation.x, _x.pathRequest.startingPose.orientation.y, _x.pathRequest.startingPose.orientation.z, _x.pathRequest.startingPose.orientation.w, _x.pathRequest.goalPose.position.x, _x.pathRequest.goalPose.position.y, _x.pathRequest.goalPose.position.z, _x.pathRequest.goalPose.orientation.x, _x.pathRequest.goalPose.orientation.y, _x.pathRequest.goalPose.orientation.z, _x.pathRequest.goalPose.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_14d().pack(_x.pathRequest.startingPose.position.x, _x.pathRequest.startingPose.position.y, _x.pathRequest.startingPose.position.z, _x.pathRequest.startingPose.orientation.x, _x.pathRequest.startingPose.orientation.y, _x.pathRequest.startingPose.orientation.z, _x.pathRequest.startingPose.orientation.w, _x.pathRequest.goalPose.position.x, _x.pathRequest.goalPose.position.y, _x.pathRequest.goalPose.position.z, _x.pathRequest.goalPose.orientation.x, _x.pathRequest.goalPose.orientation.y, _x.pathRequest.goalPose.orientation.z, _x.pathRequest.goalPose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pathRequest is None:
        self.pathRequest = se2_navigation_msgs.msg.PathRequestMsg()
      end = 0
      _x = self
      start = end
      end += 112
      (_x.pathRequest.startingPose.position.x, _x.pathRequest.startingPose.position.y, _x.pathRequest.startingPose.position.z, _x.pathRequest.startingPose.orientation.x, _x.pathRequest.startingPose.orientation.y, _x.pathRequest.startingPose.orientation.z, _x.pathRequest.startingPose.orientation.w, _x.pathRequest.goalPose.position.x, _x.pathRequest.goalPose.position.y, _x.pathRequest.goalPose.position.z, _x.pathRequest.goalPose.orientation.x, _x.pathRequest.goalPose.orientation.y, _x.pathRequest.goalPose.orientation.z, _x.pathRequest.goalPose.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14d = None
def _get_struct_14d():
    global _struct_14d
    if _struct_14d is None:
        _struct_14d = struct.Struct("<14d")
    return _struct_14d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from se2_navigation_msgs/RequestPathSrvResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RequestPathSrvResponse(genpy.Message):
  _md5sum = "3a1255d4d998bd4d6585c64639b5ee9a"
  _type = "se2_navigation_msgs/RequestPathSrvResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Response
bool status
"""
  __slots__ = ['status']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RequestPathSrvResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.status is None:
        self.status = False
    else:
      self.status = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.status
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.status,) = _get_struct_B().unpack(str[start:end])
      self.status = bool(self.status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.status
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.status,) = _get_struct_B().unpack(str[start:end])
      self.status = bool(self.status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class RequestPathSrv(object):
  _type          = 'se2_navigation_msgs/RequestPathSrv'
  _md5sum = '5539d8cfd1e0b02f407ce0465be5beeb'
  _request_class  = RequestPathSrvRequest
  _response_class = RequestPathSrvResponse
